### PR TITLE
Switch to gp3 volume types and configurable I/O performance values

### PR DESCRIPTION
**Pull request by marcransome**

### CODE REVIEW

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by sienkin — DISMISSED** [review]

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Comment by ch-code-analysis** [comment]
CI: IaC Security warnings found!

**Review by sienkin — APPROVED** [review]

**Pull request merged**
